### ISSUE TITLE
Offsets incorrect

### ISSUE THREAD

**Issue by boraakoguz** [Akandesh/blazedumper#5]
Hey! The offsets seem to be wrong but I could not find the problem. I compared the config file with hazedumper and everything matches but the dumped offsets are different. You might want to take a look.

**Comment by Akandesh** [comment]
The auto dumper is broken right now, doesn't detect new updates properly for some reason and I've been too lazy to add proper debugging to find out why, so I need to manually restart it every time there's a new update now :|

I've looked through the code which detects if there's a new update and I don't see how it could've broken since when I run it it prints the correct build id but yeah, i'll update it now to write a logfile and print a bit more useful things.

btw, i've manually restarted it now so it should be up to date again.

**Comment by Akandesh** [comment]
Alright, I believe to have found the issue with why it wasn't auto updating.  It was reading buildid for an old branch instead of the latest, public one. Hopefully they don't change it again anytime soon because then I have to implement a proper parser for it but yeah, should work now.
